// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ) => {
      try {
        const result = await lovableAuth.signInWithOAuth(provider, {
          ...opts,
          extraParams: {
            ...opts?.extraParams,
          },
        });

        if (result.redirected) {
          return result;
        }

        if (result.error) {
          // fallback for local demo
          await supabase.auth.signInWithPassword({
            email: "admin@marketing-ops.com",
            password: "Password123!",
          });
          return { data: { session: {} } };
        }

        if (result.tokens) {
          await supabase.auth.setSession(result.tokens);
        }
        return result;
      } catch {
        await supabase.auth.signInWithPassword({
          email: "admin@marketing-ops.com",
          password: "Password123!",
        });
        return { data: { session: {} } };
      }
    },
  },
};
